import {
  InMemoryDbService,
  createErrorResponse,
  createObservableResponse,
  HttpMethodInterceptorArgs,
  ParsedUrl,
  RequestInfo,
  STATUS
} from 'angular-in-memory-web-api';
import {RequestMethod, ResponseOptions, URLSearchParams} from '@angular/http';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    let nodes = [
      {"group":"nodes","data":{"id":"1.1.1","size":91}},
      {"group":"nodes","data":{"id":"1.1.10","size":8}},
      {"group":"nodes","data":{"id":"1.1.8","size":31}},
      {"group":"nodes","data":{"id":"1.1.2","size":70}},
      {"group":"nodes","data":{"id":"1.1.7","size":265}},
      {"group":"nodes","data":{"id":"1.1.3","size":12}},
      {"group":"nodes","data":{"id":"1.1.4","size":6}},
      {"group":"nodes","data":{"id":"1.1.14","size":2}},
      {"group":"nodes","data":{"id":"1.1.9","size":81}},
      {"group":"nodes","data":{"id":"1.1.5","size":271}},
      {"group":"nodes","data":{"id":"1.1.11","size":6}},
      {"group":"nodes","data":{"id":"1.1.13","size":34}},
      {"group":"nodes","data":{"id":"1.1.15","size":15}},
      {"group":"nodes","data":{"id":"1.1.12","size":4}}
    ];
    let edges = [
      {"group":"edges","data":{"id":"(1.1.2,1.1.3)","size":9,"source":"1.1.2","target":"1.1.3"}},
      {"group":"edges","data":{"id":"(1.1.15,1.1.7)","size":1,"source":"1.1.15","target":"1.1.7"}},
      {"group":"edges","data":{"id":"(1.1.12,1.1.15)","size":2,"source":"1.1.12","target":"1.1.15"}},
      {"group":"edges","data":{"id":"(1.1.15,1.1.9)","size":4,"source":"1.1.15","target":"1.1.9"}},
      {"group":"edges","data":{"id":"(1.1.7,1.1.8)","size":4,"source":"1.1.7","target":"1.1.8"}},
      {"group":"edges","data":{"id":"(1.1.3,1.1.7)","size":9,"source":"1.1.3","target":"1.1.7"}}
    ];
    let ecod = [
      { id: '1.1',
        nodes: nodes,
        edges: edges
      }
    ];

    let alignments = [
      {
        "dom1": "e1a1fA2",
        "dom2": "e1a1fA1",
        "hhEVal": 1.2e-9,
        "algLen": 27,
        "idPer": 56,
        "simPer": 1.058,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 27,
        "dom2Start": 1,
        "dom2End": 29,
        "dom1AA": "KPFQCR--ICMRNFSRSDHLTTHIRTHTG",
        "dom2AA": "RPYACPVESCDRRFSDSSNLTRHIRIHTG",
        "hhProb": 98.87,
        "hhScore": 26.25,
        "aaLen": 27,
        "aaId": 15,
        "aaSim": 18,
        "aaGap": 0,
        "rmsd": 1.32,
        "tmscore": 0.7539,
        "maxsub": 0.9243,
        "gdtts": 0.963,
        "gdtha": 0.8704,
        "dom2_fid": "386.1.1.45",
        "dom1_fid": "386.1.1.45"
      },
      {
        "dom1": "e1a1hA3",
        "dom2": "e1a1fA2",
        "hhEVal": 1.2e-9,
        "algLen": 27,
        "idPer": 41,
        "simPer": 0.933,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 29,
        "dom2Start": 2,
        "dom2End": 28,
        "dom1AA": "RPYACPVESCDRRFSDSSNLTRHIRIHTG",
        "dom2AA": "KPFACD--ICGRKFARSDERKRHTKIHLR",
        "hhProb": 98.89,
        "hhScore": 26.81,
        "aaLen": 27,
        "aaId": 11,
        "aaSim": 16,
        "aaGap": 0,
        "rmsd": 1.702,
        "tmscore": 0.6538,
        "maxsub": 0.8793,
        "gdtts": 0.9074,
        "gdtha": 0.7778,
        "dom2_fid": "386.1.1.45",
        "dom1_fid": "386.1.1.76"
      },
      {
        "dom1": "e1a1fA2",
        "dom2": "e1a1fA1",
        "hhEVal": 3.3e-10,
        "algLen": 27,
        "idPer": 56,
        "simPer": 1.058,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 27,
        "dom2Start": 1,
        "dom2End": 29,
        "dom1AA": "KPFQCR--ICMRNFSRSDHLTTHIRTHTG",
        "dom2AA": "RPYACPVESCDRRFSDSSNLTRHIRIHTG",
        "hhProb": 98.97,
        "hhScore": 26.4,
        "aaLen": 27,
        "aaId": 15,
        "aaSim": 18,
        "aaGap": 0,
        "rmsd": 1.32,
        "tmscore": 0.7539,
        "maxsub": 0.9243,
        "gdtts": 0.963,
        "gdtha": 0.8704,
        "dom2_fid": "386.1.1.45",
        "dom1_fid": "386.1.1.45"
      },
      {
        "dom1": "e1a1hA3",
        "dom2": "e1a1fA2",
        "hhEVal": 1.3e-9,
        "algLen": 27,
        "idPer": 41,
        "simPer": 0.933,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 29,
        "dom2Start": 2,
        "dom2End": 28,
        "dom1AA": "RPYACPVESCDRRFSDSSNLTRHIRIHTG",
        "dom2AA": "KPFACD--ICGRKFARSDERKRHTKIHLR",
        "hhProb": 98.88,
        "hhScore": 26.63,
        "aaLen": 27,
        "aaId": 11,
        "aaSim": 16,
        "aaGap": 0,
        "rmsd": 1.702,
        "tmscore": 0.6538,
        "maxsub": 0.8793,
        "gdtts": 0.9074,
        "gdtha": 0.7778,
        "dom2_fid": "386.1.1.45",
        "dom1_fid": "386.1.1.76"
      },
      {
        "dom1": "e1a1hA3",
        "dom2": "e1a1fA1",
        "hhEVal": 2.9e-11,
        "algLen": 27,
        "idPer": 48,
        "simPer": 0.929,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 27,
        "dom2Start": 2,
        "dom2End": 28,
        "dom1AA": "KPFQCRICMRNFSRSDHLTTHIRTHTG",
        "dom2AA": "KPFACDICGRKFARSDERKRHTKIHLR",
        "hhProb": 99.11,
        "hhScore": 29.28,
        "aaLen": 27,
        "aaId": 13,
        "aaSim": 15,
        "aaGap": 0,
        "rmsd": 0.98,
        "tmscore": 0.7709,
        "maxsub": 0.9348,
        "gdtts": 0.9722,
        "gdtha": 0.8704,
        "dom2_fid": "386.1.1.45",
        "dom1_fid": "386.1.1.76"
      },
      {
        "dom1": "e1a1hA3",
        "dom2": "e1a1fA1",
        "hhEVal": 7.5e-12,
        "algLen": 27,
        "idPer": 48,
        "simPer": 0.929,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 27,
        "dom2Start": 2,
        "dom2End": 28,
        "dom1AA": "KPFQCRICMRNFSRSDHLTTHIRTHTG",
        "dom2AA": "KPFACDICGRKFARSDERKRHTKIHLR",
        "hhProb": 99.19,
        "hhScore": 29.31,
        "aaLen": 27,
        "aaId": 13,
        "aaSim": 15,
        "aaGap": 0,
        "rmsd": 0.98,
        "tmscore": 0.7709,
        "maxsub": 0.9348,
        "gdtts": 0.9722,
        "gdtha": 0.8704,
        "dom2_fid": "386.1.1.45",
        "dom1_fid": "386.1.1.76"
      },
      {
        "dom1": "e1a2oA1",
        "dom2": "e1a04A2",
        "hhEVal": 1e-19,
        "algLen": 122,
        "idPer": 26,
        "simPer": 0.41,
        "gapPer": 0,
        "dom1Start": 2,
        "dom1End": 124,
        "dom2Start": 3,
        "dom2End": 135,
        "dom1AA": "PATILLIDDHPMLRTGVKQLISMAPDITVVGEASNGEQGIELAESLDPDLILLDLNMPGMNGLETLDKLREKSLSGRIVVFSVSNHE--EDVVTALKRGADGYLLKDME---------PEDLLKALHQAAAGEM",
        "dom2AA": "KIRVLSVDDSALMRQIMTEIINSHSDMEMVATAPDPLVARDLIKKFNPDVLTLDVEMPRMDGLDFLEKLMRLRP-MPVVMVSSLTGKGSEVTLRALELGAIDFVTKPQLGIREGMLAYSEMIAEKVRTAARARI",
        "hhProb": 99.61,
        "hhScore": 115.17,
        "aaLen": 122,
        "aaId": 32,
        "aaSim": 63,
        "aaGap": 0,
        "rmsd": 2.969,
        "tmscore": 0.7687,
        "maxsub": 0.6928,
        "gdtts": 0.7029,
        "gdtha": 0.4918,
        "dom2_fid": "2007.4.1.8",
        "dom1_fid": "2007.4.1.8"
      },
      {
        "dom1": "e1a2oA1",
        "dom2": "e1a04A2",
        "hhEVal": 3e-20,
        "algLen": 122,
        "idPer": 26,
        "simPer": 0.41,
        "gapPer": 0,
        "dom1Start": 2,
        "dom1End": 124,
        "dom2Start": 3,
        "dom2End": 135,
        "dom1AA": "PATILLIDDHPMLRTGVKQLISMAPDITVVGEASNGEQGIELAESLDPDLILLDLNMPGMNGLETLDKLREKSLSGRIVVFSVSNHE--EDVVTALKRGADGYLLKDME---------PEDLLKALHQAAAGEM",
        "dom2AA": "KIRVLSVDDSALMRQIMTEIINSHSDMEMVATAPDPLVARDLIKKFNPDVLTLDVEMPRMDGLDFLEKLMRLRP-MPVVMVSSLTGKGSEVTLRALELGAIDFVTKPQLGIREGMLAYSEMIAEKVRTAARARI",
        "hhProb": 99.64,
        "hhScore": 115.84,
        "aaLen": 122,
        "aaId": 32,
        "aaSim": 63,
        "aaGap": 0,
        "rmsd": 2.969,
        "tmscore": 0.7687,
        "maxsub": 0.6928,
        "gdtts": 0.7029,
        "gdtha": 0.4918,
        "dom2_fid": "2007.4.1.8",
        "dom1_fid": "2007.4.1.8"
      },
      {
        "dom1": "e1a3xA3",
        "dom2": "e1a04A2",
        "hhEVal": 4,
        "algLen": 68,
        "idPer": 10,
        "simPer": 0.039,
        "gapPer": 0,
        "dom1Start": 43,
        "dom1End": 116,
        "dom2Start": 23,
        "dom2End": 92,
        "dom1AA": "LAESLDPDLILLDLNMPGMNGLETLDKLREKSLSGRIVVFSVSNHEEDVVTALKRGADGYLLKD--MEPEDLLKAL",
        "dom2AA": "AVFEQKAKAIIVLST-----SGTTPRLVSKYRPNCPIILVTRCPRAA-RFSHLYRGVFPFVFEKETDDVEARINFG",
        "hhProb": 60.01,
        "hhScore": 24.6,
        "aaLen": 68,
        "aaId": 7,
        "aaSim": 21,
        "aaGap": 0,
        "rmsd": 4.309,
        "tmscore": 0.5516,
        "maxsub": 0.5169,
        "gdtts": 0.636,
        "gdtha": 0.4228,
        "dom2_fid": "2007.4.1.8",
        "dom1_fid": "2111.8.1.1"
      },
      {
        "dom1": "e1a3xA3",
        "dom2": "e1a04A2",
        "hhEVal": 8.6,
        "algLen": 69,
        "idPer": 10,
        "simPer": 0.074,
        "gapPer": 0,
        "dom1Start": 41,
        "dom1End": 115,
        "dom2Start": 21,
        "dom2End": 91,
        "dom1AA": "IELAESLDPDLILLDLNMPGMNGLETLDKLREKSLSGRIVVFSVSNHEEDVVTALKRGADGYLLKD--MEPEDLLKA",
        "dom2AA": "VAAVFEQKAKAIIVLST-----SGTTPRLVSKYRPNCPIILVTRCPRAA-RFSHLYRGVFPFVFEKETDDVEARINF",
        "hhProb": 48.13,
        "hhScore": 24.56,
        "aaLen": 69,
        "aaId": 7,
        "aaSim": 22,
        "aaGap": 0,
        "rmsd": 4.307,
        "tmscore": 0.5499,
        "maxsub": 0.5173,
        "gdtts": 0.6341,
        "gdtha": 0.4203,
        "dom2_fid": "2007.4.1.8",
        "dom1_fid": "2111.8.1.1"
      },
      {
        "dom1": "e1a3xA5",
        "dom2": "e1a04A2",
        "hhEVal": 6.7,
        "algLen": 81,
        "idPer": 12,
        "simPer": 0.111,
        "gapPer": 0,
        "dom1Start": 36,
        "dom1End": 116,
        "dom2Start": 32,
        "dom2End": 124,
        "dom1AA": "NGEQGIELAESLDPDLILLDLNMPGMNG-LETLDKLREKSLS-----GRIVV-----FSVSNHEEDVVTALKRGADGYL-LKDMEPEDLLKAL",
        "dom2AA": "NNPETLVALRKAGLNIVRMNFSHGSYEYHKSVIDNARKSEELYPGRPLAIALDTKGPALSEKDKEDLRFGVKNGVHMVFASFIRTANDVLTIR",
        "hhProb": 52.12,
        "hhScore": 27.16,
        "aaLen": 81,
        "aaId": 10,
        "aaSim": 25,
        "aaGap": 0,
        "rmsd": 5.661,
        "tmscore": 0.4865,
        "maxsub": 0.4345,
        "gdtts": 0.5,
        "gdtha": 0.3117,
        "dom2_fid": "2007.4.1.8",
        "dom1_fid": "2002.1.1.220"
      },
      {
        "dom1": "e1a53A1",
        "dom2": "e1a3xA5",
        "hhEVal": 0.32,
        "algLen": 164,
        "idPer": 10,
        "simPer": 0.122,
        "gapPer": 0,
        "dom1Start": 34,
        "dom1End": 233,
        "dom2Start": 66,
        "dom2End": 234,
        "dom1AA": "PETLVALRKAGLNIVRMNFSHGSYEYHKSVIDNARKSEELYPGRPLAIALDTKGPALSEKDKEDLRFGVKNGVHMVFA--SFIRTANDVLTIREVLGEQGKDVKIIVKIENQQGVNNFDEILKV-TDGVMVARGDLGIEIPAPEVLAVQKKLIAKSNLA--GKPVICATQMLESMTYNPRPTRAEVSDVGNAILDGADCVMLSGE",
        "dom2AA": "IEYSKFMERY-AVGLSILTEEKYFNG---SYETLRKIASS-VS--IPILM-----KDFIVKESQIDDAYNLGADTVLLIVKIL-TERELESLLEYARSYG--MEPLIEINDEN---DLDIALRIGARFIGINSRDLET-L-EINK----ENQRKLISMIPSNVVKVAESG---------ISER---NEIEELRKLGVNAFLIGSS",
        "hhProb": 94.37,
        "hhScore": 42.23,
        "aaLen": 164,
        "aaId": 16,
        "aaSim": 55,
        "aaGap": 0,
        "rmsd": 4.7,
        "tmscore": 0.6833,
        "maxsub": 0.5126,
        "gdtts": 0.5762,
        "gdtha": 0.3659,
        "dom2_fid": "2002.1.1.220",
        "dom1_fid": "2002.1.1.111"
      },
      {
        "dom1": "e1a53A1",
        "dom2": "e1a3xA5",
        "hhEVal": 0.36,
        "algLen": 115,
        "idPer": 11,
        "simPer": 0.152,
        "gapPer": 0,
        "dom1Start": 32,
        "dom1End": 164,
        "dom2Start": 113,
        "dom2End": 234,
        "dom1AA": "NNPETLVALRKAGLNIVRMNFSHGSYEYHKSVIDNARKSEELYPGRPLAIALDTKGPALSEKDKEDLRFGVKNGVHMVFASFIRT---ANDVLTIREVLGEQGKDVKIIVKIENQQGVNNFDEILKV----TDGVMVARG",
        "dom2AA": "VKESQIDDAYNLGADTVLLIVKILTER---ELESLLEYARSY--G--MEPLI-----EIN--DENDLDIALRIGARFIGINSRDLETLEINKENQRKLISMIPSNVV--KVAE--SGISERNEIEELRKLGVNAFLIGSS",
        "hhProb": 92.77,
        "hhScore": 41.95,
        "aaLen": 115,
        "aaId": 13,
        "aaSim": 41,
        "aaGap": 0,
        "rmsd": 5.183,
        "tmscore": 0.5801,
        "maxsub": 0.4332,
        "gdtts": 0.5283,
        "gdtha": 0.3196,
        "dom2_fid": "2002.1.1.220",
        "dom1_fid": "2002.1.1.111"
      },
      {
        "dom1": "e1a53A1",
        "dom2": "e1a3xA5",
        "hhEVal": 0.42,
        "algLen": 166,
        "idPer": 12,
        "simPer": 0.151,
        "gapPer": 0,
        "dom1Start": 34,
        "dom1End": 233,
        "dom2Start": 66,
        "dom2End": 234,
        "dom1AA": "PETLVALRKAGLNIVRMNFSHGSYEYHKSVIDNARKSEELYPGRPLAIALDTKGPALSEKDKEDLRFGVKNGVHMVFA--SFIRTANDVLTIREVLGEQGKDVKIIVKIENQQGVNNFDEILKV-TDGVMVARGDLGIEIPAPEVLAVQKKLIAKSNLAGKPVICATQMLESMTYNPRPTRAEVSDVGNAILDGADCVMLSGE",
        "dom2AA": "IEYSKFMERY-AVGLSILTEEKYFNG---SYETLRKIASS-VS--IPILM-----KDFIVKESQIDDAYNLGADTVLLIVKIL-TERELESLLEYARSYG--MEPLIEINDEN---DLDIALRIGARFIGINSRDLET-LE-INK-ENQRKLISMIP-SNVVKVAESG---------ISER---NEIEELRKLGVNAFLIGSS",
        "hhProb": 94.35,
        "hhScore": 40.88,
        "aaLen": 166,
        "aaId": 20,
        "aaSim": 59,
        "aaGap": 0,
        "rmsd": 4.424,
        "tmscore": 0.709,
        "maxsub": 0.5382,
        "gdtts": 0.5934,
        "gdtha": 0.3795,
        "dom2_fid": "2002.1.1.220",
        "dom1_fid": "2002.1.1.111"
      },
      {
        "dom1": "e1a53A1",
        "dom2": "e1a3xA5",
        "hhEVal": 0.47,
        "algLen": 115,
        "idPer": 11,
        "simPer": 0.166,
        "gapPer": 0,
        "dom1Start": 32,
        "dom1End": 164,
        "dom2Start": 113,
        "dom2End": 234,
        "dom1AA": "NNPETLVALRKAGLNIVRMNFSHGSYEYHKSVIDNARKSEELYPGRPLAIALDTKGPALSEKDKEDLRFGVKNGVHMVFASFIRT---ANDVLTIREVLGEQGKDVKIIVKIENQQGVNNFDEILKV----TDGVMVARG",
        "dom2AA": "VKESQIDDAYNLGADTVLLIVKILTER---ELESLLEYARSY--G--MEPLI-----EIN--DENDLDIALRIGARFIGINSRDLETLEINKENQRKLISMIPSNV--VKVAE--SGISERNEIEELRKLGVNAFLIGSS",
        "hhProb": 92.28,
        "hhScore": 40.59,
        "aaLen": 115,
        "aaId": 13,
        "aaSim": 42,
        "aaGap": 0,
        "rmsd": 5.243,
        "tmscore": 0.575,
        "maxsub": 0.4296,
        "gdtts": 0.5239,
        "gdtha": 0.3152,
        "dom2_fid": "2002.1.1.220",
        "dom1_fid": "2002.1.1.111"
      },
      {
        "dom1": "e1a5zA2",
        "dom2": "e1a4iA1",
        "hhEVal": 0.0000019,
        "algLen": 33,
        "idPer": 18,
        "simPer": 0.186,
        "gapPer": 0,
        "dom1Start": 40,
        "dom1End": 73,
        "dom2Start": 1,
        "dom2End": 35,
        "dom1AA": "RHAVVVGRSKIVGAPMHDLLLWNNA--TVTTCHSKT",
        "dom2AA": "MKIGIVGLGR-VGSSTAFALLMKGFAREMVLIDVDK",
        "hhProb": 98.23,
        "hhScore": 55.16,
        "aaLen": 33,
        "aaId": 6,
        "aaSim": 10,
        "aaGap": 0,
        "rmsd": 1.597,
        "tmscore": 0.6649,
        "maxsub": 0.859,
        "gdtts": 0.8788,
        "gdtha": 0.7273,
        "dom2_fid": "2003.1.1.61",
        "dom1_fid": "2003.1.1.40"
      },
      {
        "dom1": "e1a5zA2",
        "dom2": "e1a4iA1",
        "hhEVal": 0.00001,
        "algLen": 33,
        "idPer": 18,
        "simPer": 0.199,
        "gapPer": 0,
        "dom1Start": 41,
        "dom1End": 74,
        "dom2Start": 2,
        "dom2End": 36,
        "dom1AA": "HAVVVGRSKIVGAPMHDLLLWNNA--TVTTCHSKTA",
        "dom2AA": "KIGIVGLGR-VGSSTAFALLMKGFAREMVLIDVDKK",
        "hhProb": 97.98,
        "hhScore": 56.08,
        "aaLen": 33,
        "aaId": 6,
        "aaSim": 10,
        "aaGap": 0,
        "rmsd": 2.379,
        "tmscore": 0.6439,
        "maxsub": 0.8317,
        "gdtts": 0.8636,
        "gdtha": 0.7121,
        "dom2_fid": "2003.1.1.61",
        "dom1_fid": "2003.1.1.40"
      },
      {
        "dom1": "e1a6dB2",
        "dom2": "e1a6dA2",
        "hhEVal": 2.2e-31,
        "algLen": 104,
        "idPer": 45,
        "simPer": 0.673,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 104,
        "dom2Start": 3,
        "dom2End": 107,
        "dom1AA": "TDDATLRKIALTALSGKNTGLSNDFLADLVVKAVNAVAEVRDGKTIVDTANIKVDKKNGGSVNDTQFISAVSILIR-GGTDHVVSEVERALNDAIRVVAITKEDG",
        "dom2AA": "DEKALLLKMAQTSLNSKSASVAKDKLAEISYEAVKSVAELRDGKYYVDFDNIQVVKKQGGAIDDTQLINKAVSILVRGETEHVVDEMERSITDSLHVVASALEDG",
        "hhProb": 99.97,
        "hhScore": 176.7,
        "aaLen": 104,
        "aaId": 47,
        "aaSim": 72,
        "aaGap": 0,
        "rmsd": 1.535,
        "tmscore": 0.8988,
        "maxsub": 0.8764,
        "gdtts": 0.8894,
        "gdtha": 0.7188,
        "dom2_fid": "2498.5.1.2",
        "dom1_fid": "2498.5.1.2"
      },
      {
        "dom1": "e1a6dB2",
        "dom2": "e1a6dA2",
        "hhEVal": 2.2e-32,
        "algLen": 104,
        "idPer": 45,
        "simPer": 0.673,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 104,
        "dom2Start": 3,
        "dom2End": 107,
        "dom1AA": "TDDATLRKIALTALSGKNTGLSNDFLADLVVKAVNAVAEVRDGKTIVDTANIKVDKKNGGSVNDTQFISAVSILIR-GGTDHVVSEVERALNDAIRVVAITKEDG",
        "dom2AA": "DEKALLLKMAQTSLNSKSASVAKDKLAEISYEAVKSVAELRDGKYYVDFDNIQVVKKQGGAIDDTQLINKAVSILVRGETEHVVDEMERSITDSLHVVASALEDG",
        "hhProb": 99.98,
        "hhScore": 176.58,
        "aaLen": 104,
        "aaId": 47,
        "aaSim": 72,
        "aaGap": 0,
        "rmsd": 1.535,
        "tmscore": 0.8988,
        "maxsub": 0.8764,
        "gdtts": 0.8894,
        "gdtha": 0.7188,
        "dom2_fid": "2498.5.1.2",
        "dom1_fid": "2498.5.1.2"
      },
      {
        "dom1": "e1a6dB3",
        "dom2": "e1a6dB2",
        "hhEVal": 0.98,
        "algLen": 43,
        "idPer": 21,
        "simPer": 0.225,
        "gapPer": 0,
        "dom1Start": 15,
        "dom1End": 66,
        "dom2Start": 74,
        "dom2End": 117,
        "dom1AA": "SLNSKSASVA-KDKLAEISYEAVKSVAELRDGKYYVDFDNIQVVKKQGGAIDD",
        "dom2AA": "VITQKGIDDMAQHYLSRAGIYAVRRVKKS---------DMDKLAKATGASIVS",
        "hhProb": 76.15,
        "hhScore": 31.32,
        "aaLen": 43,
        "aaId": 9,
        "aaSim": 17,
        "aaGap": 0,
        "rmsd": 10.403,
        "tmscore": 0.223,
        "maxsub": 0.2507,
        "gdtts": 0.314,
        "gdtha": 0.2442,
        "dom2_fid": "2498.5.1.2",
        "dom1_fid": "2487.1.1.35"
      },
      {
        "dom1": "e1a6dB3",
        "dom2": "e1a6dB2",
        "hhEVal": 1.4,
        "algLen": 42,
        "idPer": 21,
        "simPer": 0.226,
        "gapPer": 0,
        "dom1Start": 15,
        "dom1End": 65,
        "dom2Start": 74,
        "dom2End": 116,
        "dom1AA": "SLNSKSASVA-KDKLAEISYEAVKSVAELRDGKYYVDFDNIQVVKKQGGAID",
        "dom2AA": "VITQKGIDDMAQHYLSRAGIYAVRRVKKS---------DMDKLAKATGASIV",
        "hhProb": 71.94,
        "hhScore": 30.5,
        "aaLen": 42,
        "aaId": 9,
        "aaSim": 17,
        "aaGap": 0,
        "rmsd": 10.271,
        "tmscore": 0.2257,
        "maxsub": 0.2566,
        "gdtts": 0.3214,
        "gdtha": 0.25,
        "dom2_fid": "2498.5.1.2",
        "dom1_fid": "2487.1.1.35"
      },
      {
        "dom1": "e1a6dB3",
        "dom2": "e1a6dA2",
        "hhEVal": 0.000023,
        "algLen": 47,
        "idPer": 26,
        "simPer": 0.266,
        "gapPer": 0,
        "dom1Start": 10,
        "dom1End": 65,
        "dom2Start": 71,
        "dom2End": 118,
        "dom1AA": "ALTALSGKNTGLSN-DFLADLVVKAVNAVAEVRDGKTIVDTANIKVDKKNGGSVNDT",
        "dom2AA": "ANVVITQKGIDDMAQHYLSRAGIYAVRRVKKS-------DM--DKLAKATGASIVST",
        "hhProb": 97.38,
        "hhScore": 54.34,
        "aaLen": 47,
        "aaId": 12,
        "aaSim": 20,
        "aaGap": 0,
        "rmsd": 11.22,
        "tmscore": 0.2271,
        "maxsub": 0.2371,
        "gdtts": 0.3085,
        "gdtha": 0.2287,
        "dom2_fid": "2498.5.1.2",
        "dom1_fid": "2487.1.1.35"
      },
      {
        "dom1": "e1a6dB3",
        "dom2": "e1a6dA2",
        "hhEVal": 0.000028,
        "algLen": 47,
        "idPer": 26,
        "simPer": 0.266,
        "gapPer": 0,
        "dom1Start": 10,
        "dom1End": 65,
        "dom2Start": 71,
        "dom2End": 118,
        "dom1AA": "ALTALSGKNTGLSN-DFLADLVVKAVNAVAEVRDGKTIVDTANIKVDKKNGGSVNDT",
        "dom2AA": "ANVVITQKGIDDMAQHYLSRAGIYAVRRVKKS-------DM--DKLAKATGASIVST",
        "hhProb": 97.33,
        "hhScore": 52.63,
        "aaLen": 47,
        "aaId": 12,
        "aaSim": 20,
        "aaGap": 0,
        "rmsd": 11.22,
        "tmscore": 0.2271,
        "maxsub": 0.2371,
        "gdtts": 0.3085,
        "gdtha": 0.2287,
        "dom2_fid": "2498.5.1.2",
        "dom1_fid": "2487.1.1.35"
      },
      {
        "dom1": "e1a6eA1",
        "dom2": "e1a6dB1",
        "hhEVal": 1.6e-72,
        "algLen": 241,
        "idPer": 62,
        "simPer": 0.975,
        "gapPer": 0,
        "dom1Start": 1,
        "dom1End": 242,
        "dom2Start": 5,
        "dom2End": 245,
        "dom1AA": "KDAMKENIEAAIAISNSVRSSLGPRGMDKMLVDSLGDIVITNDGVTILKEMDVEHPAAKMMVEVSKTQDSFVGDGTTTAVIIAGGLLQQAQGLINQNVHPTVISEGYRMASEEAKRVIDEISTKIAYAAGGGATAAEIAFRLRSYAQKIGGRQQLAIEKFADAIEEIPRALAENAGLDPIDILLKLRAEHAKGNKTYGINVFTGEIEDMVKNGVIEPIRVGKQAIESATEAAIMILRIDDVI",
        "dom2AA": "KNAQRNNIEAAKAIADAVRTTLGPKGMDKMLVDSIGDIIISNDGATILKEMDVEHPTAKMIVEVSKAQDTAVGDGTTTAVVLSGELLKQAETLLDQGVHPTVISNGYRLAVNEARKIIDEIAEK-SFLWGGGAVEAELAMRLAKYANSVGGREQLAIEAFAKALEIIPRTLAENAGIDPINTLIKLKADDEKGRISVGVDLDNNGVGDMKAKGVVDPLRVKTHALESAVEVATMILRIDDVI",
        "hhProb": 100,
        "hhScore": 497.04,
        "aaLen": 241,
        "aaId": 149,
        "aaSim": 194,
        "aaGap": 0,
        "rmsd": 1.395,
        "tmscore": 0.9584,
        "maxsub": 0.9008,
        "gdtts": 0.9232,
        "gdtha": 0.7583,
        "dom2_fid": "593.1.1.1",
        "dom1_fid": "593.1.1.1"
      },
      {
        "dom1": "e1a6eA1",
        "dom2": "e1a6dB1",
        "hhEVal": 3.2e-73,
        "algLen": 240,
        "idPer": 62,
        "simPer": 0.975,
        "gapPer": 0,
        "dom1Start": 2,
        "dom1End": 242,
        "dom2Start": 6,
        "dom2End": 245,
        "dom1AA": "DAMKENIEAAIAISNSVRSSLGPRGMDKMLVDSLGDIVITNDGVTILKEMDVEHPAAKMMVEVSKTQDSFVGDGTTTAVIIAGGLLQQAQGLINQNVHPTVISEGYRMASEEAKRVIDEISTKIAYAAGGGATAAEIAFRLRSYAQKIGGRQQLAIEKFADAIEEIPRALAENAGLDPIDILLKLRAEHAKGNKTYGINVFTGEIEDMVKNGVIEPIRVGKQAIESATEAAIMILRIDDVI",
        "dom2AA": "NAQRNNIEAAKAIADAVRTTLGPKGMDKMLVDSIGDIIISNDGATILKEMDVEHPTAKMIVEVSKAQDTAVGDGTTTAVVLSGELLKQAETLLDQGVHPTVISNGYRLAVNEARKIIDEIAEK-SFLWGGGAVEAELAMRLAKYANSVGGREQLAIEAFAKALEIIPRTLAENAGIDPINTLIKLKADDEKGRISVGVDLDNNGVGDMKAKGVVDPLRVKTHALESAVEVATMILRIDDVI",
        "hhProb": 100,
        "hhScore": 493.77,
        "aaLen": 240,
        "aaId": 148,
        "aaSim": 193,
        "aaGap": 0,
        "rmsd": 1.398,
        "tmscore": 0.9582,
        "maxsub": 0.9005,
        "gdtts": 0.9229,
        "gdtha": 0.7573,
        "dom2_fid": "593.1.1.1",
        "dom1_fid": "593.1.1.1"
      },
      {
        "dom1": "e1a6jA1",
        "dom2": "e1a3aA1",
        "hhEVal": 6.4e-33,
        "algLen": 139,
        "idPer": 23,
        "simPer": 0.369,
        "gapPer": 0,
        "dom1Start": 3,
        "dom1End": 144,
        "dom2Start": 6,
        "dom2End": 149,
        "dom1AA": "KLGAENIFLGRKAATKEEAIRFAGEQLVK-GGYVEPEYVQAMLDREKLTPTYLGESIAVPHGTVEAKDR-VLKTGVVFCQYPEGVRFGEEEDDIARLVIGIAARN---NEHIQVITSLTNALDDESVIERLAHTTSVDEVLELLAGR",
        "dom2AA": "VLNRECTRSRVHCQSKKRALEIISELAAKQLSLPPQVVFEAILTREKMGSTGIGNGIAIPHGKLE---EDTLRAVGVFVQLETPIAFDAIDNQPVDLLFALLVPADQTKTHLHTLSLVAKRLADKTICRRLRAAQSDEELYQIITDT",
        "hhProb": 100,
        "hhScore": 188.88,
        "aaLen": 139,
        "aaId": 32,
        "aaSim": 59,
        "aaGap": 0,
        "rmsd": 2.757,
        "tmscore": 0.8096,
        "maxsub": 0.7112,
        "gdtts": 0.7302,
        "gdtha": 0.518,
        "dom2_fid": "311.1.1.2",
        "dom1_fid": "311.1.1.2"
      },
      {
        "dom1": "e1a6jA1",
        "dom2": "e1a3aA1",
        "hhEVal": 8.8e-33,
        "algLen": 139,
        "idPer": 23,
        "simPer": 0.369,
        "gapPer": 0,
        "dom1Start": 3,
        "dom1End": 144,
        "dom2Start": 6,
        "dom2End": 149,
        "dom1AA": "KLGAENIFLGRKAATKEEAIRFAGEQLVK-GGYVEPEYVQAMLDREKLTPTYLGESIAVPHGTVEAKDR-VLKTGVVFCQYPEGVRFGEEEDDIARLVIGIAARN---NEHIQVITSLTNALDDESVIERLAHTTSVDEVLELLAGR",
        "dom2AA": "VLNRECTRSRVHCQSKKRALEIISELAAKQLSLPPQVVFEAILTREKMGSTGIGNGIAIPHGKLE---EDTLRAVGVFVQLETPIAFDAIDNQPVDLLFALLVPADQTKTHLHTLSLVAKRLADKTICRRLRAAQSDEELYQIITDT",
        "hhProb": 100,
        "hhScore": 188.77,
        "aaLen": 139,
        "aaId": 32,
        "aaSim": 59,
        "aaGap": 0,
        "rmsd": 2.757,
        "tmscore": 0.8096,
        "maxsub": 0.7112,
        "gdtts": 0.7302,
        "gdtha": 0.518,
        "dom2_fid": "311.1.1.2",
        "dom1_fid": "311.1.1.2"
      },
      {
        "dom1": "e1a6zA1",
        "dom2": "e1a6uL1",
        "hhEVal": 0.066,
        "algLen": 25,
        "idPer": 20,
        "simPer": 0.416,
        "gapPer": 0,
        "dom1Start": 14,
        "dom1End": 39,
        "dom2Start": 14,
        "dom2End": 38,
        "dom1AA": "GETVTLTCRSSTGAVTTSNYANWVQE",
        "dom2AA": "SSVTTLRCRALNYYP-QNITMKWLKD",
        "hhProb": 95.55,
        "hhScore": 29.82,
        "aaLen": 25,
        "aaId": 5,
        "aaSim": 10,
        "aaGap": 0,
        "rmsd": 3.802,
        "tmscore": 0.3466,
        "maxsub": 0.6614,
        "gdtts": 0.69,
        "gdtha": 0.51,
        "dom2_fid": "11.1.1.179",
        "dom1_fid": "11.1.1.26"
      },
      {
        "dom1": "e1a6zA1",
        "dom2": "e1a6uL1",
        "hhEVal": 0.13,
        "algLen": 25,
        "idPer": 20,
        "simPer": 0.416,
        "gapPer": 0,
        "dom1Start": 14,
        "dom1End": 39,
        "dom2Start": 14,
        "dom2End": 38,
        "dom1AA": "GETVTLTCRSSTGAVTTSNYANWVQE",
        "dom2AA": "SSVTTLRCRALNYYP-QNITMKWLKD",
        "hhProb": 94.82,
        "hhScore": 29.57,
        "aaLen": 25,
        "aaId": 5,
        "aaSim": 10,
        "aaGap": 0,
        "rmsd": 3.802,
        "tmscore": 0.3466,
        "maxsub": 0.6614,
        "gdtts": 0.69,
        "gdtha": 0.51,
        "dom2_fid": "11.1.1.179",
        "dom1_fid": "11.1.1.26"
      },
      {
        "dom1": "e1a7bC1",
        "dom2": "e1a6zA1",
        "hhEVal": 0.000022,
        "algLen": 68,
        "idPer": 7,
        "simPer": 0.039,
        "gapPer": 0,
        "dom1Start": 14,
        "dom1End": 85,
        "dom2Start": 7,
        "dom2End": 79,
        "dom1AA": "SSVTTLRCRALNYYPQNITMKWLKDKQPMDAKEFEPKDVLPNGDGTYQG-----WITLAVPPGEEQRYTCQVEHPGL",
        "dom2AA": "GHGINLNIPNFQMTDDIDEVRWERGSTLVAEF--KR--KPFLKSGAFEILANGDLKIKNLTRDDSGTYNVTVYSTNG",
        "hhProb": 98.07,
        "hhScore": 43.93,
        "aaLen": 68,
        "aaId": 5,
        "aaSim": 14,
        "aaGap": 0,
        "rmsd": 19.122,
        "tmscore": 0.2594,
        "maxsub": 0.2473,
        "gdtts": 0.2868,
        "gdtha": 0.1912,
        "dom2_fid": "11.1.1.26",
        "dom1_fid": "11.1.1.179"
      },
      {
        "dom1": "e1a7bC1",
        "dom2": "e1a6zA1",
        "hhEVal": 0.0000026,
        "algLen": 69,
        "idPer": 7,
        "simPer": 0.039,
        "gapPer": 0,
        "dom1Start": 14,
        "dom1End": 86,
        "dom2Start": 7,
        "dom2End": 80,
        "dom1AA": "SSVTTLRCRALNYYPQNITMKWLKDKQPMDAKEFEPKDVLPNGDGTYQG-----WITLAVPPGEEQRYTCQVEHPGLD",
        "dom2AA": "GHGINLNIPNFQMTDDIDEVRWERGSTLVAEF--KR--KPFLKSGAFEILANGDLKIKNLTRDDSGTYNVTVYSTNGT",
        "hhProb": 98.39,
        "hhScore": 43.5,
        "aaLen": 69,
        "aaId": 5,
        "aaSim": 14,
        "aaGap": 0,
        "rmsd": 19.046,
        "tmscore": 0.2574,
        "maxsub": 0.2437,
        "gdtts": 0.2826,
        "gdtha": 0.1884,
        "dom2_fid": "11.1.1.26",
        "dom1_fid": "11.1.1.179"
      },
      {
        "dom1": "e1a7bC1",
        "dom2": "e1a6uL1",
        "hhEVal": 4.1e-11,
        "algLen": 76,
        "idPer": 11,
        "simPer": 0.109,
        "gapPer": 0,
        "dom1Start": 9,
        "dom1End": 94,
        "dom2Start": 2,
        "dom2End": 77,
        "dom1AA": "LTTSPGETVTLTCRSSTGAVTTSNYANWVQEKPDHLFTGLIGGTNNRAPGVPARFSGSLIGNKAALTITGAQTEDEAIYFCALWYS",
        "dom2AA": "VWGALGHGINLNIPNFQMT-DDIDEVRWERGS--T---LVAEFKR-KPFLKSGAFEILA---NGDLKIKNLTRDDSGTYNVTVYST",
        "hhProb": 99.25,
        "hhScore": 66.67,
        "aaLen": 76,
        "aaId": 8,
        "aaSim": 20,
        "aaGap": 0,
        "rmsd": 18.903,
        "tmscore": 0.3968,
        "maxsub": 0.3888,
        "gdtts": 0.4145,
        "gdtha": 0.3191,
        "dom2_fid": "11.1.1.179",
        "dom1_fid": "11.1.1.179"
      },
      {
        "dom1": "e1a7bC1",
        "dom2": "e1a6uL1",
        "hhEVal": 4.8e-12,
        "algLen": 76,
        "idPer": 11,
        "simPer": 0.109,
        "gapPer": 0,
        "dom1Start": 9,
        "dom1End": 94,
        "dom2Start": 2,
        "dom2End": 77,
        "dom1AA": "LTTSPGETVTLTCRSSTGAVTTSNYANWVQEKPDHLFTGLIGGTNNRAPGVPARFSGSLIGNKAALTITGAQTEDEAIYFCALWYS",
        "dom2AA": "VWGALGHGINLNIPNFQMT-DDIDEVRWERGS--T---LVAEFKR-KPFLKSGAFEILA---NGDLKIKNLTRDDSGTYNVTVYST",
        "hhProb": 99.37,
        "hhScore": 66.08,
        "aaLen": 76,
        "aaId": 8,
        "aaSim": 20,
        "aaGap": 0,
        "rmsd": 18.903,
        "tmscore": 0.3968,
        "maxsub": 0.3888,
        "gdtts": 0.4145,
        "gdtha": 0.3191,
        "dom2_fid": "11.1.1.179",
        "dom1_fid": "11.1.1.179"
      },
      {
        "dom1": "e1a7iA2",
        "dom2": "e1a7iA1",
        "hhEVal": 0.028,
        "algLen": 27,
        "idPer": 15,
        "simPer": 0.517,
        "gapPer": 0,
        "dom1Start": 2,
        "dom1End": 28,
        "dom2Start": 1,
        "dom2End": 27,
        "dom1AA": "KCGACGRTVYHAEEVQCDGRSFHRCCF",
        "dom2AA": "LCMVCRKNLDSTTVAIHDAEVYCKSCY",
        "hhProb": 93.85,
        "hhScore": 22.61,
        "aaLen": 27,
        "aaId": 4,
        "aaSim": 9,
        "aaGap": 0,
        "rmsd": 2.541,
        "tmscore": 0.3307,
        "maxsub": 0.6386,
        "gdtts": 0.7315,
        "gdtha": 0.537,
        "dom2_fid": "377.1.1.25",
        "dom1_fid": "377.1.1.38"
      },
      {
        "dom1": "e1a7iA2",
        "dom2": "e1a7iA1",
        "hhEVal": 0.046,
        "algLen": 27,
        "idPer": 15,
        "simPer": 0.517,
        "gapPer": 0,
        "dom1Start": 2,
        "dom1End": 28,
        "dom2Start": 1,
        "dom2End": 27,
        "dom1AA": "KCGACGRTVYHAEEVQCDGRSFHRCCF",
        "dom2AA": "LCMVCRKNLDSTTVAIHDAEVYCKSCY",
        "hhProb": 93.06,
        "hhScore": 21.49,
        "aaLen": 27,
        "aaId": 4,
        "aaSim": 9,
        "aaGap": 0,
        "rmsd": 2.541,
        "tmscore": 0.3307,
        "maxsub": 0.6386,
        "gdtts": 0.7315,
        "gdtha": 0.537,
        "dom2_fid": "377.1.1.25",
        "dom1_fid": "377.1.1.38"
      },
      {
        "dom1": "e1a7sA1",
        "dom2": "e1a5h.1",
        "hhEVal": 3.8e-39,
        "algLen": 214,
        "idPer": 30,
        "simPer": 0.533,
        "gapPer": 0,
        "dom1Start": 8,
        "dom1End": 259,
        "dom2Start": 1,
        "dom2End": 215,
        "dom1AA": "IKGGLFADIASHPWQAAIFAKHRRSPGERFLCGGILISSCWILSAAHCFQERFPPHHLTVILGRTYRVVPGEEEQKFEVEKYIVHKEFDDDTYDNDIALLQLKSDSSRCAQESSVVRTVCLPPADLQLPDWTECELSGYGKHEALSPFYSERLKEAHVRLYPSSRCTSQHLLNRTVTDNMLCAGDTRSGGPQANLHDACQGDSGGPLVCLNDGRMTLVGIISWGLG-CGQKDVPGVYTKVTNYLDWIRDNMRP",
        "dom2AA": "IVGGRKARPRQFPFLASIQNQ------GRHFCGGALIHARFVMTAASCFPG-----VSTVVLGAYDLRRRERQSRQTFSISSMSENGYDPQQNLNDLMLLQLDRE----ANLTSSVTILPLPLQNATVEAGTRCQVAGWGSQRSGG-RLSRFPRFVNVTVTPEDQCR----------PNNVCTGVLT------RRGGICNGDGGTPLVCEG----LAHGVASFSLGPCGR-G-PDFFTRVALFRDWIDGVLNN",
        "hhProb": 100,
        "hhScore": 261.37,
        "aaLen": 214,
        "aaId": 64,
        "aaSim": 101,
        "aaGap": 0,
        "rmsd": 1.894,
        "tmscore": 0.9167,
        "maxsub": 0.8203,
        "gdtts": 0.8283,
        "gdtha": 0.6402,
        "dom2_fid": "1.1.5.152",
        "dom1_fid": "1.1.5.154"
      },
      {
        "dom1": "e1a7sA1",
        "dom2": "e1a5h.1",
        "hhEVal": 5.2e-41,
        "algLen": 213,
        "idPer": 30,
        "simPer": 0.537,
        "gapPer": 0,
        "dom1Start": 8,
        "dom1End": 258,
        "dom2Start": 1,
        "dom2End": 214,
        "dom1AA": "IKGGLFADIASHPWQAAIFAKHRRSPGERFLCGGILISSCWILSAAHCFQERFPPHHLTVILGRTYRVVPGEEEQKFEVEKYIVHKEFDDDTYDNDIALLQLKSDSSRCAQESSVVRTVCLPPADLQLPDWTECELSGYGKHEALSPFYSERLKEAHVRLYPSSRCTSQHLLNRTVTDNMLCAGDTRSGGPQANLHDACQGDSGGPLVCLNDGRMTLVGIISWGLG-CGQKDVPGVYTKVTNYLDWIRDNMR",
        "dom2AA": "IVGGRKARPRQFPFLASIQNQ------GRHFCGGALIHARFVMTAASCFPG-----VSTVVLGAYDLRRRERQSRQTFSISSMSENGYDPQQNLNDLMLLQLDRE----ANLTSSVTILPLPLQNATVEAGTRCQVAGWGSQRSGG-RLSRFPRFVNVTVTPEDQCR----------PNNVCTGVLT------RRGGICNGDGGTPLVCEG----LAHGVASFSLGPCGR-G-PDFFTRVALFRDWIDGVLN",
        "hhProb": 100,
        "hhScore": 259.79,
        "aaLen": 213,
        "aaId": 64,
        "aaSim": 101,
        "aaGap": 0,
        "rmsd": 1.863,
        "tmscore": 0.9184,
        "maxsub": 0.8237,
        "gdtts": 0.831,
        "gdtha": 0.6432,
        "dom2_fid": "1.1.5.152",
        "dom1_fid": "1.1.5.154"
      },
      {
        "dom1": "e1a81E1",
        "dom2": "e1a1aA1",
        "hhEVal": 5e-33,
        "algLen": 98,
        "idPer": 31,
        "simPer": 0.509,
        "gapPer": 0,
        "dom1Start": 2,
        "dom1End": 104,
        "dom2Start": 3,
        "dom2End": 100,
        "dom1AA": "QAEEWYFGKITRRESERLLLNAENPRGTFLVRESETTKGAYSLSVSDFDNAKGLNVKHYKIRKLDSGGFYITSRTQFNSLQQLVAYYSKHADGLCHRLTTVCP",
        "dom2AA": "NHLPFFFGNITREEAEDYLVQGGMSDGLYLLRQSRNYLGGFALSVAH-----GRKAHHYTIERELNGTYAIAGGRTHASPADLCHYHSQESDGLVCLLKKPFN",
        "hhProb": 100,
        "hhScore": 174.84,
        "aaLen": 98,
        "aaId": 30,
        "aaSim": 46,
        "aaGap": 0,
        "rmsd": 1.648,
        "tmscore": 0.8837,
        "maxsub": 0.8635,
        "gdtts": 0.8776,
        "gdtha": 0.7117,
        "dom2_fid": "214.1.1.4",
        "dom1_fid": "214.1.1.4"
      },
      {
        "dom1": "e1a81E1",
        "dom2": "e1a1aA1",
        "hhEVal": 8.5e-35,
        "algLen": 98,
        "idPer": 31,
        "simPer": 0.509,
        "gapPer": 0,
        "dom1Start": 2,
        "dom1End": 104,
        "dom2Start": 3,
        "dom2End": 100,
        "dom1AA": "QAEEWYFGKITRRESERLLLNAENPRGTFLVRESETTKGAYSLSVSDFDNAKGLNVKHYKIRKLDSGGFYITSRTQFNSLQQLVAYYSKHADGLCHRLTTVCP",
        "dom2AA": "NHLPFFFGNITREEAEDYLVQGGMSDGLYLLRQSRNYLGGFALSVAH-----GRKAHHYTIERELNGTYAIAGGRTHASPADLCHYHSQESDGLVCLLKKPFN",
        "hhProb": 100,
        "hhScore": 175.12,
        "aaLen": 98,
        "aaId": 30,
        "aaSim": 46,
        "aaGap": 0,
        "rmsd": 1.648,
        "tmscore": 0.8837,
        "maxsub": 0.8635,
        "gdtts": 0.8776,
        "gdtha": 0.7117,
        "dom2_fid": "214.1.1.4",
        "dom1_fid": "214.1.1.4"
      },
      {
        "dom1": "e1a8lA2",
        "dom2": "e1a8lA1",
        "hhEVal": 3.9e-20,
        "algLen": 90,
        "idPer": 22,
        "simPer": 0.372,
        "gapPer": 0,
        "dom1Start": 19,
        "dom1End": 112,
        "dom2Start": 12,
        "dom2End": 106,
        "dom1AA": "KMVNPVKLIVFVRKDHCQYCDQLKQLVQELSELTD-----KLSYEIVDFDTPEGKELAKRYRIDRAPATTITQDGKDFGVRYFGLPAGHEFAAFLEDIV",
        "dom2AA": "NIDQDVRILVF-VTPTCPYCPLAVRMAHKFAIENTKAGKGKILGDMVEAI--EYPEWADQYNVMAVPKIVIQVNGEDR-VEFEGAYPEKMFLEKLLSAL",
        "hhProb": 99.63,
        "hhScore": 103.95,
        "aaLen": 90,
        "aaId": 20,
        "aaSim": 38,
        "aaGap": 0,
        "rmsd": 2.33,
        "tmscore": 0.7665,
        "maxsub": 0.7066,
        "gdtts": 0.7417,
        "gdtha": 0.5278,
        "dom2_fid": "2485.1.1.54",
        "dom1_fid": "2485.1.1.42"
      },
    ];

    return {ecod, alignments};
  }
}

export class InMemoryDataServiceOverride extends InMemoryDataService {
  // parseUrl override
  parseUrl(url: string): ParsedUrl {
    try {
      const loc = this.getLocation(url);
      let drop = 0;
      let urlRoot = '';
      if (loc.host !== undefined) {
        // url for a server on a different host!
        // assume it's collection is actually here too.
        drop = 1; // the leading slash
        urlRoot = loc.protocol + '//' + loc.host + '/';
      }
      const path = loc.pathname.substring(drop);
      let [base, collectionName, id] = path.split('/');
      const resourceUrl = urlRoot + base + '/' + collectionName + '/';
      [collectionName] = collectionName.split('.'); // ignore anything after the '.', e.g., '.json'
      const query = loc.search && new URLSearchParams(loc.search.substr(1));

      const result = { base, collectionName, id, query, resourceUrl };
      console.log('override parseUrl:');
      console.log(result);
      return result;
    } catch (err) {
      const msg = `unable to parse url '${url}'; original error: ${err.message}`;
      throw new Error(msg);
    }
  }

  // intercept response from the default HTTP method handlers
  responseInterceptor(response: ResponseOptions, reqInfo: RequestInfo) {
    const method = RequestMethod[reqInfo.req.method].toUpperCase();
    const body = JSON.stringify(response.body);
    console.log(`responseInterceptor: ${method} ${reqInfo.req.url}: \n${body}`);
    return response;
  }

  // remark: HTTP GET interceptor
  protected get(interceptorArgs: HttpMethodInterceptorArgs) {

    console.log('HTTP GET override');
    let resp: ResponseOptions;

    const {id, query, collection, collectionName, headers} = interceptorArgs.requestInfo;
    let data = collection;

    console.log("data is:");
    console.log(data);

    if (id) {
      data = this.findById(collection, id);
    } else if (query) {
      data = this.applyQuery(collection, query);
    }

    if (data) {
      resp = new ResponseOptions({
        body: { data: this.clone(data) },
        headers: headers,
        status: STATUS.OK
      });
    } else {
      resp = createErrorResponse(STATUS.NOT_FOUND,
        `'${collectionName}' with id='${id}' not found`);
    }

    return createObservableResponse(resp);
  }

  /////////// private ///////////////
  private applyQuery(collection: any[], query: URLSearchParams) {
    // extract filtering conditions - {propertyName, RegExps) - from query/search parameters
    const conditions: {name: string, rx: RegExp}[] = [];
    const caseSensitive = 'i';
    query.paramsMap.forEach((value: string[], name: string) => {
      value.forEach(v => conditions.push({name, rx: new RegExp(decodeURI(v), caseSensitive)}));
    });

    const len = conditions.length;
    if (!len) { return collection; }

    // remark: AND the RegExp conditions
    return collection.filter(row => {
      let ok = true;
      let i = len;
      while (ok && i) {
        i -= 1;
        const cond = conditions[i];
        ok = cond.rx.test(row[cond.name]);
      }
      return ok;
    });
  }

  private clone(data: any) {
    return JSON.parse(JSON.stringify(data));
  }

  private findById(collection: any[], id: number | string) {
    return collection.find((item: any) => item.id === id);
  }

  private getLocation(href: string) {
    const l = document.createElement('a');
    l.href = href;
    return l;
  };
}
